/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Elin (https://sketchfab.com/ElinHohler)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/vr-gallery-house-baked-8e3b280476eb4790af97e2abd3d9be59
title: VR Gallery House (baked)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/vr.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Floor_0" position={[-3.23, 0, 4.05]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.FloorBaked} />
              </group>
              <group name="Glass_1" position={[-3.18, 0, 4.05]} rotation={[0, Math.PI / 2, 0]}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.Glass} />
              </group>
              <group name="Pictures_2" position={[-0.07, 1.41, 4.14]} rotation={[0, Math.PI / 2, 0]} scale={0.55}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Picture_Frame} />
                <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Image_H_01} />
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Image_V_01} />
                <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Image_H_02} />
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.Image_V_02} />
                <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.Image_H_03} />
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.Image_V_03} />
                <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.Image_H_04} />
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.Image_H_05} />
                <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.Image_V_04} />
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.Image_H_06} />
                <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.Image_H_07} />
                <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.Image_H_08} />
                <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.Image_V_05} />
                <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.Image_H_09} />
              </group>
              <group name="DecoLamp_3" position={[0, 1.06, -9.22]}>
                <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.DecoLampBaked} />
              </group>
              <group name="Sky_4" position={[-0.27, 18.92, -5.76]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
                <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.material} />
              </group>
              <group name="Terasse_Baked_5">
                <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.Terasse_baked} />
              </group>
              <group name="Walls_6" position={[-3.23, 0, 4.05]} rotation={[0, Math.PI / 2, 0]}>
                <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.WallBaked} />
              </group>
              <group name="Wood_7" position={[-3.23, 0, 4.05]}>
                <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.WoodBaked} />
              </group>
              <group name="8x8001_73" position={[7.74, 1.37, 2.55]} rotation={[-Math.PI, -0.87, -Math.PI]} scale={0.63}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="Sprite_8x8001_72" />
                  <skinnedMesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.material_22} skeleton={nodes.Object_37.skeleton} />
                </group>
              </group>
              <group name="8x8_139" position={[7.75, 1.37, -2.59]} rotation={[-Math.PI, 0.99, -Math.PI]} scale={0.63}>
                <group name="GLTF_created_1">
                  <primitive object={nodes.GLTF_created_1_rootJoint} />
                  <group name="Sprite_8x8_138" />
                  <skinnedMesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.material_22} skeleton={nodes.Object_106.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/vr.glb')
